baseurl = "https://ioos.github.io"
CanonifyUrls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "en-us"
[params]
  Title = "IOOS GITHUB PAGES"
  Tagline = "Entry point for IOOS resources on GitHub"
[params.Github]
  Head = "new-website"
  Url = "https://github.com/ioos/ioos.github.io"
[[menu.extramedia]]
    name = ""
    url = ""
    weight = -110
    identifier = ""
[[menu.extramedia]]
    name = ""
    weight = -200

	
 
