baseurl = "http://ioos.github.io/ioos.github.io"
languageCode = "en-us"
title = "IOOS GitHub Site" 
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
[params]
 Description = "Collection of IOOS documentation and software"
 Copyright = "(c) 2014 Integrated Ocean Observing System. Rights reserved."

